### ISSUE TITLE
AttributeError: 'tqdm' object has no attribute 'disable'

### ISSUE THREAD

**Issue by Sreekar33** [ZZprogrammer/DBVSR#1]
Error occurs at File /DBVSR/code/trainer/trainer_dbvsr.py", line 80, in test
    tqdm_test = tqdm(self.loader_test, ncols=80)

**Comment by cscss** [comment]
https://stackoverflow.com/questions/56794127/python-progressbar-tqdm
I hope this can help you.

**Comment by Sreekar33** [comment]
It was very much helpful, Thanks
